'use client'

import { useEffect, useState } from 'react'
import { categoryLabel, computeInsights, formatCo2e } from '@/lib/insights'
import type { ActivityRecord, CoachNudge } from '@/lib/types'

/**
 * The Coach Agent's overnight nudge — the "works while you sleep" payoff.
 * Calls the Coach Agent with a grounded summary of the user's logged activity
 * once there's data; degrades to a gentle placeholder when empty or unavailable.
 */
export function CoachCard({ activities }: { activities: ActivityRecord[] }) {
  const [nudge, setNudge] = useState<CoachNudge | null>(null)
  const [state, setState] = useState<'loading' | 'ready' | 'unavailable'>('loading')

  useEffect(() => {
    if (activities.length === 0) {
      setState('unavailable')
      return
    }
    let active = true
    const insights = computeInsights(activities)
    const summary =
      `${activities.length} activities, ${formatCo2e(insights.total)} total` +
      (insights.topSource
        ? `; top source ${categoryLabel(insights.topSource.category)} (${insights.topSource.pct.toFixed(0)}%)`
        : '')
    fetch('/api/v1/coach/nudge', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        activity_summary: summary,
        top_categories: insights.topSource ? categoryLabel(insights.topSource.category) : '',
      }),
    })
      .then((r) => (r.ok ? r.json() : null))
      .then((data: CoachNudge | null) => {
        if (!active) return
        if (data?.message) {
          setNudge(data)
          setState('ready')
        } else {
          setState('unavailable')
        }
      })
      .catch(() => {
        if (active) setState('unavailable')
      })
    return () => {
      active = false
    }
  }, [activities])

  return (
    <section
      aria-label="Overnight coach insight"
      className="relative overflow-hidden rounded-glass border border-neon-purple/25 bg-[linear-gradient(135deg,rgba(123,97,255,0.12),rgba(0,245,212,0.04))] p-5 shadow-glass"
    >
      <div
        aria-hidden="true"
        className="pointer-events-none absolute -right-12 -top-12 h-32 w-32 rounded-full bg-neon-purple/30 blur-3xl"
      />
      <div className="relative flex items-center gap-2">
        <span className="text-lg" aria-hidden="true">🧠</span>
        <h2 className="eyebrow text-neon-purple">AI Coach · for your data</h2>
      </div>

      {state === 'ready' && nudge ? (
        <>
          <p className="relative mt-3 text-sm leading-relaxed text-text-primary">{nudge.message}</p>
          {nudge.offset_suggestion && (
            <p className="relative mt-2 text-sm leading-relaxed text-text-secondary">
              <span className="font-semibold text-eco-lime">Offset:</span> {nudge.offset_suggestion}
            </p>
          )}
          <div className="relative mt-4 flex items-center gap-3">
            <span className="rounded-full border border-eco-lime/30 bg-eco-lime/10 px-3 py-1 font-mono text-[11px] text-eco-lime">
              ↓ {nudge.estimated_saving_pct}% potential
            </span>
            <span className="font-mono text-[11px] text-text-muted">generated by AI from your activity</span>
          </div>
        </>
      ) : state === 'unavailable' ? (
        <p className="relative mt-3 text-sm leading-relaxed text-text-secondary">
          Your Coach writes a personalised weekly brief once you&apos;ve logged a few activities. Snap or
          describe your first one to get started.
        </p>
      ) : (
        <div className="relative mt-3 space-y-2" aria-hidden="true">
          <div className="h-3 w-full animate-pulse rounded bg-white/[0.06]" />
          <div className="h-3 w-4/5 animate-pulse rounded bg-white/[0.06]" />
          <div className="h-3 w-2/3 animate-pulse rounded bg-white/[0.06]" />
        </div>
      )}
    </section>
  )
}
